
[Patch]
# The level of girl power you get from estrogen patches
# Range: 1 ~ 255
# Default: 1
girlPowerLevel = 1
# Enable the estrogen patch to drain
# Default: true
drain = true
# The amount of ticks it takes for the estrogen patches to drain a millibucket
# Min: 0
# Default: 144
drainSpeed = 144

[ThighHighs]
# The amount of Fall Damage Reduction Thigh Highs add
# Range: 0 ~ 1000
# Default: 100
fallDamageReduction = 100
# The chance for the Pride Thigh Highs to spawn in chests (in % per container)
# Range: 0 ~ 100
# Default: 10
prideThighHighsChance = 10

# Settings for the dream block

[DreamBlock]
# Horizontal range from a dream block in which the dreaming effect can be applied to sleeping players
# Default: 10
dreamingEffectRange = 10
# Chance for a random tick to cause the dreaming effect to be applied in percent
# Range: 0 ~ 100
# Default: 25
dreamingTickChance = 25
# Range from a dream catcher for a player to be to block the Dreaming Effect
# Default: 10
dreamCatcherRange = 10

# Settings which are more fun and not fit for survival

[Minigame]
# Enable/Disable all minigame settings
# Default: false
enabled = false
# Gives you permanent, unremovable Girl Power effect
# Default: false
permaDash = false
# The level of Girl Power Effect when Perma-Dash is enabled
# Range: 0 ~ 255
# Default: 1
permaDashLevel = 1

# Bug fixes and other improvements related to this mod

[Fixes]
# Fix a dupe glitch related to Jukeboxes and stacks
# Default: true
jukeboxFix = true